"""
Supabase PostgreSQL Manager for HealthGuard AI
Provides cloud PostgreSQL database connection, Row Level Security (RLS) setup,
and full CRUD operational adapters for HealthGuard AI.
"""

import os
import sys
from typing import Dict, Any, List, Optional
from datetime import datetime

try:
    from supabase import create_client, Client
    SUPABASE_SDK_AVAILABLE = True
except ImportError:
    SUPABASE_SDK_AVAILABLE = False
    Client = Any


def get_supabase_client() -> Optional[Client]:
    """Retrieve initialized Supabase Client if URL and Key exist."""
    if not SUPABASE_SDK_AVAILABLE:
        return None

    url = os.getenv("SUPABASE_URL", "").strip()
    key = os.getenv("SUPABASE_KEY", "").strip() or os.getenv("SUPABASE_ANON_KEY", "").strip()

    if not url or not key or url.startswith("your_") or key.startswith("your_"):
        return None

    if not url.startswith("http://") and not url.startswith("https://"):
        url = f"https://{url}.supabase.co"

    try:
        return create_client(url, key)
    except Exception:
        return None


def is_supabase_active() -> bool:
    """Check if Supabase is active and reachable."""
    client = get_supabase_client()
    return client is not None


def get_supabase_schema_sql() -> str:
    """
    Return complete PostgreSQL SQL DDL to execute in Supabase SQL Editor.
    Creates all 13 healthcare tables with foreign keys and Row Level Security (RLS).
    """
    return """
-- 🏥 HealthGuard AI — Supabase PostgreSQL Database DDL & Schema Setup

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    password_hash TEXT,
    firebase_uid TEXT,
    age INT,
    gender TEXT,
    weight_kg NUMERIC(5,2),
    height_cm NUMERIC(5,2),
    blood_group TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Medications Table
CREATE TABLE IF NOT EXISTS medications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    dosage TEXT NOT NULL,
    frequency TEXT NOT NULL,
    time_slots JSONB NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    notes TEXT,
    is_active INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Medication Logs Table
CREATE TABLE IF NOT EXISTS medication_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medication_id BIGINT REFERENCES medications(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    scheduled_at TIMESTAMPTZ NOT NULL,
    taken_at TIMESTAMPTZ,
    status TEXT DEFAULT 'pending',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Health Metrics Table
CREATE TABLE IF NOT EXISTS health_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    metric_type TEXT NOT NULL,
    value NUMERIC(10,2) NOT NULL,
    value2 NUMERIC(10,2),
    unit TEXT NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Health Goals Table
CREATE TABLE IF NOT EXISTS health_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    goal_type TEXT NOT NULL,
    target_value NUMERIC(10,2) NOT NULL,
    current_value NUMERIC(10,2) DEFAULT 0,
    unit TEXT NOT NULL,
    deadline DATE,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Nutrition Logs Table
CREATE TABLE IF NOT EXISTS nutrition_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    meal_type TEXT NOT NULL,
    calories NUMERIC(8,2) NOT NULL,
    protein_g NUMERIC(6,2),
    carbs_g NUMERIC(6,2),
    fat_g NUMERIC(6,2),
    food_items TEXT,
    recorded_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Chat History Table
CREATE TABLE IF NOT EXISTS chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Indian Medications Catalog Table (1mg)
CREATE TABLE IF NOT EXISTS indian_medications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name TEXT NOT NULL,
    generic_name TEXT NOT NULL,
    manufacturer TEXT,
    price_inr NUMERIC(10,2) NOT NULL,
    form TEXT,
    strength TEXT,
    usage_purpose TEXT,
    side_effects TEXT,
    substitutes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Ayurvedic Herbs Table
CREATE TABLE IF NOT EXISTS ayurvedic_herbs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sanskrit_name TEXT,
    primary_benefit TEXT NOT NULL,
    dosha_balancing TEXT,
    recommended_dosage TEXT,
    precautions TEXT,
    formulation TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Doctor Appointments Table (Practo)
CREATE TABLE IF NOT EXISTS doctor_appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    doctor_name TEXT NOT NULL,
    specialty TEXT NOT NULL,
    clinic_hospital TEXT,
    city TEXT DEFAULT 'Mumbai',
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    status TEXT DEFAULT 'Scheduled',
    fee_inr NUMERIC(10,2) DEFAULT 500.0,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Insurance Policies Table (ABHA)
CREATE TABLE IF NOT EXISTS insurance_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    provider_name TEXT NOT NULL,
    policy_number TEXT NOT NULL,
    abha_id TEXT,
    coverage_amount NUMERIC(12,2) NOT NULL,
    expiry_date DATE,
    network_hospitals TEXT,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Family Members Table
CREATE TABLE IF NOT EXISTS family_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    relationship TEXT NOT NULL,
    age INT,
    gender TEXT,
    blood_group TEXT,
    medical_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. Caregiver Contacts & Health Alerts
CREATE TABLE IF NOT EXISTS caregiver_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    relationship TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    notify_critical INT DEFAULT 1,
    notify_missed INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS health_alerts_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    alert_type TEXT NOT NULL,
    metric_name TEXT,
    value NUMERIC(10,2),
    threshold TEXT,
    severity TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE health_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE medications ENABLE ROW LEVEL SECURITY;
ALTER TABLE family_members ENABLE ROW LEVEL SECURITY;
"""
